# Generated by Django 5.0.6 on 2024-10-24 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lessoncontent_options_contenthistory_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='notification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='api.notification'),
        ),
    ]
